services:
  postgres:
    image: postgres:14.18-bookworm
    container_name: postgres_spring_student_backend_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: springpg123*
      POSTGRES_DB: studentdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: